version: '3.8'

services:
  node_app:
    build: .
    container_name: node_container
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    restart: always
