server:
  port: 8080

resilience4j:
  circuitbreaker:
    instances:
      externalService:
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s

resilience4j.retry:
  instances:
    myRetry:
      max-attempts: 3
      wait-duration: 2s

management:
  endpoints:
    web:
      exposure:
        include: "*"
